# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lrucache_pb2 as lrucache__pb2


class DownloadImageStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestDownloadImage = channel.unary_unary(
                '/lrucache.DownloadImage/RequestDownloadImage',
                request_serializer=lrucache__pb2.ImageRequest.SerializeToString,
                response_deserializer=lrucache__pb2.ImageResponse.FromString,
                )


class DownloadImageServicer(object):
    """The greeting service definition.
    """

    def RequestDownloadImage(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DownloadImageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestDownloadImage': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestDownloadImage,
                    request_deserializer=lrucache__pb2.ImageRequest.FromString,
                    response_serializer=lrucache__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lrucache.DownloadImage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DownloadImage(object):
    """The greeting service definition.
    """

    @staticmethod
    def RequestDownloadImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lrucache.DownloadImage/RequestDownloadImage',
            lrucache__pb2.ImageRequest.SerializeToString,
            lrucache__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
